[build]
  command = """
    curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.549/quarto-1.4.549-linux-amd64.deb
    sudo dpkg -i quarto-1.4.549-linux-amd64.deb
    quarto render
  """
  publish = "_site"
